module.exports = {
  comercial: [
    'Redacción de contratos comerciales',
    'Ejecución de alquileres y expensas',
    'Ejecución de cheques y pagares',
    'Ejecución de Sentencias y Honorarios',
    'Concursos y Quiebras',
    'Defensa del Consumidor',
    'Actualización de Datos Comerciales (Veraz, Nosis, Banco Central, etc.)',
    'Negociación de Deudas Comerciales',
    'Gestión de Embargos e Inhibiciones',
  ],
  civil: [
    'Accidentes de Tránsito',
    'Sucesiones',
    'Divorcios',
    'Redacción de todo tipo de contratos, compra-venta, cesiones, convenios privados, boletos, etc.',
    'Daños y perjuicios',
    'Desalojos, Convenio de desocupación',
    'Mala Praxis, Amparos de Salud',
    'Usucapión',
    'Reivindicación de Inmuebles',
    ' Interdictos y Posesorios',
  ],
  laboral: {
    trabajadores: [
      'Despidos',
      'Trabajo en negro',
      'Cálculo de Indemnizaciones laborales',
      'Accidentes de trabajo (ART), Enfermedad Profesional, Accidente In Itinere, Enfermedad por COVID-19',
      'Discriminación laboral',
      'Horas extras y/o nocturnas impagas',
      'Diferencias salariales',
      'Mobbing- Acoso Laboral o Sexual.',
      'Tutela Sindical',
    ],
    empleadores: [
      'Redacción de Contratos de Trabajo y confección de legajos.',
      'Negociación y representación en conflictos colectivos de trabajo.',
      'Diseño e implementación de políticas de personal y estructuración de los recursos humanos.',
      'Asesoramiento en materia de convenios colectivos de empresa.',
      'Asesoramiento en procesos judiciales en Capital Federal y Gran Buenos Aires por despidos directos e indirectos, responsabilidad solidaria, accidentes y enfermedades de trabajo, accidentes y/o enfermedades inculpables, seguridad e higiene en el trabajo.',
      'Representación extrajudicial ante reclamos administrativos (Ministerio de Trabajo y SECLO).',
      'Asistencia en acciones de exclusión de tutela gremial y prácticas antisindicales.',
      'Negociación con entidades gremiales en caso de huelgas y todo otro tipo de medidas de fuerza o acción directa.',
      'Representación de empresas en cámaras de la actividad.',
    ],
  },
  penal: [
    'Excarcelaciones, Eximición de Prisión, Hábeas corpus, Querellas, Particular Damnificado.',
    'Asistencia a audiencias, comisarias y unidades penitenciarias.',
    'Suspensión de Juicio a Prueba, Flagrancia, Juicio Abreviado, Probation.',
    'Libertad condicional, Libertad Asistida, Salidas transitorias.',
    'Asistencia ante Allanamiento de domicilio.',
    'Robos, hurtos, Usurpación, Violencia de género, Piratas del Asfalto.',
    'Estupefacientes, Narcomenudeo.',
    'Delitos Sexuales, Delitos Informáticos, Calumnias e Injurias.',
    'Delitos Contravencionales, Secuestros, Extorsión, Estafas, Asociación Ilícita.',
  ],
};
